CREATE TABLE merchants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_code VARCHAR(20) NOT NULL,
    legal_name VARCHAR(150) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    merchant_category_code VARCHAR(4) NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_merchants_merchant_code UNIQUE (merchant_code)
);
