CREATE TABLE card_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(30) NOT NULL,
    credit_limit NUMERIC(19,2) NOT NULL,
    current_balance NUMERIC(19,2) NOT NULL,
    available_credit NUMERIC(19,2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    status VARCHAR(255) NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_card_accounts_account_number UNIQUE (account_number),
    CONSTRAINT ck_card_accounts_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELINQUENT', 'CLOSED'))
);
