CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_reference VARCHAR(30) NOT NULL,
    last_four VARCHAR(4) NOT NULL,
    expiration_month INTEGER NOT NULL,
    expiration_year INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    card_account_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_cards_card_reference UNIQUE (card_reference),
    CONSTRAINT ck_cards_status
        CHECK (status IN ('ACTIVE', 'BLOCKED', 'EXPIRED', 'REPLACED', 'CLOSED')),
    CONSTRAINT fk_cards_card_account
        FOREIGN KEY (card_account_id) REFERENCES card_accounts (id)
);
