CREATE TABLE authorizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorization_reference VARCHAR(50) NOT NULL,
    card_id BIGINT NOT NULL,
    merchant_id BIGINT NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    authorization_type VARCHAR(255) NOT NULL,
    channel VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_authorizations_authorization_reference UNIQUE (authorization_reference),
    CONSTRAINT ck_authorizations_authorization_type
        CHECK (authorization_type IN ('PURCHASE', 'CASH_WITHDRAWAL')),
    CONSTRAINT ck_authorizations_channel
        CHECK (channel IN ('POS', 'ECOMMERCE', 'ATM', 'PAYPAL', 'ALIPAY')),
    CONSTRAINT ck_authorizations_status
        CHECK (status IN ('PENDING', 'APPROVED', 'DECLINED')),
    CONSTRAINT fk_authorizations_card
        FOREIGN KEY (card_id) REFERENCES cards (id),
    CONSTRAINT fk_authorizations_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchants (id)
);
