ALTER TABLE authorizations
    DROP CONSTRAINT ck_authorizations_status;

ALTER TABLE authorizations
    ADD CONSTRAINT ck_authorizations_status
        CHECK (status IN ('PENDING', 'APPROVED', 'DECLINED', 'REVERSED'));

CREATE TABLE authorization_reversals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reversal_reference VARCHAR(50) NOT NULL,
    authorization_id BIGINT NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_authorization_reversals_reversal_reference UNIQUE (reversal_reference),
    CONSTRAINT ck_authorization_reversals_status
        CHECK (status IN ('PENDING', 'COMPLETED')),
    CONSTRAINT fk_authorization_reversals_authorization
        FOREIGN KEY (authorization_id) REFERENCES authorizations (id)
);
