ALTER TABLE authorizations
    DROP CONSTRAINT ck_authorizations_status;

ALTER TABLE authorizations
    ADD CONSTRAINT ck_authorizations_status
        CHECK (status IN ('PENDING', 'APPROVED', 'DECLINED', 'REVERSED', 'CLEARED'));

CREATE TABLE clearings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clearing_reference VARCHAR(50) NOT NULL,
    authorization_id BIGINT NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_clearings_clearing_reference UNIQUE (clearing_reference),
    CONSTRAINT ck_clearings_status CHECK (status IN ('PENDING')),
    CONSTRAINT fk_clearings_authorization
        FOREIGN KEY (authorization_id) REFERENCES authorizations (id)
);
